/* Generating date to a particular number of days */
import java.util.Scanner;
class Scenario_2
{
    public static void main(String[] args) 
    {
        int a,b,c,d,e,f,g,h,i,j,k;
        System.out.println("enter the number of days:");
        System.out.println("enter the year:");
        Scanner sc=new Scanner(System.in);
        int days=sc.nextInt();
        int year=sc.nextInt();
        if(year%4==0)
        {
            if(days>=1&&days<=31)
            {
                System.out.println(days+"jan");
            }
            if(days>=32&&days<=60)
            {
                a=days-31;
                System.out.println(a+"feb");
            }
            if(days>=61&&days<=91)
            {
                b=days-60;
                System.out.println(b+"mar");
            }
            if(days>=92&&days<=121)
            {
                c=days-91;
                System.out.println(c+"apr");
            }
            if(days>=122&&days<=152)
            {
                d=days-121;
                System.out.println(d+"may");
            }
            if(days>=153&&days<=182)
            {
                e=days-152;
                System.out.println(e+"jun");
            }
            if(days>=183&&days<=213)
            {
                f=days-182;
                System.out.println(f+"jul");
            }
            if(days>=214&&days<=244)
            {
                g=days-213;
                System.out.println(g+"aug");
            }
            if(days>=245&&days<=274)
            {
                h=days-244;
                System.out.println(h+"sep");
            }
            if(days>=275&&days<=305)
            {
                i=days-274;
                System.out.println(i+"oct");
            }
            if(days>=306&&days<=335)
            {
                j=days-305;
                System.out.println(j+"nov");
            }
            if(days>=336&&days<=366)
            {
                k=days-335;
                System.out.println(k+"dec");
            }
        }
        else
        {
            if(days>=1&&days<=31)
            {
                System.out.println(days+"jan");
            }
            if(days>=32&&days<=59)
            {
                a=days-31;
                System.out.println(a+"feb");
            }
            if(days>=60&&days<=90)
            {
                b=days-59;
                System.out.println(b+"mar");
            }
            if(days>=91&&days<=120)
            {
                c=days-90;
                System.out.println(c+"apr");
            }
            if(days>=121&&days<=151)
            {
                d=days-120;
                System.out.println(d+"may");
            }
            if(days>=152&&days<=181)
            {
                e=days-151;
                System.out.println(e+"jun");
            }
            if(days>=182&&days<=212)
            {
                f=days-181;
                System.out.println(f+"jul");
            }
            if(days>=213&&days<=243)
            {
                g=days-212;
                System.out.println(g+"aug");
            }
            if(days>=244&&days<=273)
            {
                h=days-243;
                System.out.println(h+"sep");
            }
            if(days>=274&&days<=304)
            {
                i=days-273;
                System.out.println(i+"oct");
            }
            if(days>=305&&days<=334)
            {
                j=days-304;
                System.out.println(j+"nov");
            }
            if(days>=335&&days<=365)
            {
                k=days-334;
                System.out.println(k+"dec");
            }
        }
    }
}
